services:
  admin:
    build:
      context: .
      dockerfile: admin/dockerfile
    ports:
      - 8502:8502
    depends_on:
      - mongo

  app:
    build:
      context: .
      dockerfile: app/dockerfile
    ports:
      - 8501:8501
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
