services:
  admin:
    build:
      context: .
      dockerfile: admin/dockerfile
    ports:
      - 8502:8502
    volumes:
      - ./admin:/app
    depends_on:
      - mongo

  app:
    build:
      context: .
      dockerfile: app/dockerfile
    ports:
      - 8501:8501
    volumes:
      - ./app:/app
    depends_on:
      - mongo
      - admin

  mongo:
    image: mongo
    restart: always
